import 'package:flutter/material.dart';
import 'package:visit_kudus/helper/items.dart';
import 'package:visit_kudus/helper/models.dart';
import 'package:visit_kudus/screens/details.dart';

void main() {
  runApp(new MaterialApp(
    title: 'Home',
    home: Home(),
  ));
}

class Home extends StatelessWidget {
  final GlobalKey _scaffoldKey = GlobalKey();

  List<Models> data = [
    Models(1, Colors.blueAccent, 'Museum Kretek', 'Jl. Getas Pejaten No.155, Getas, Getas Pejaten, Kec. Jati, Kabupaten Kudus, Jawa Tengah 59343', 'https://goo.gl/maps/g1Q1uHPk1ZTWoK3bA', 'assets/images/museum_kudus.jpg', 'Museum Kretek menyimpan 1.195 koleksi mengenai sejarah kretek di Kabupaten Kudus, yuk kepoin', 'Museum ini didirikan atas prakarsa dan diresmikan oleh Soepardjo Roestam, Gubernur Jawa Tengah, pada 3 Oktober 1986. Gagasan ini bermula sewaktu Beliau berkunjung ke Kudus dan menyaksikan potensi kontribusi usaha rokok kretek dalam menggerakkan perekonomian daerah.\nMuseum Kretek didirikan di atas lahan seluas 2,5 ha, dengan pembiayaan dari Persatuan Pengusaha Rokok Kudus (PPRK).'),
    Models(2, Colors.redAccent, 'Air Terjun Montel', 'Japan, Kec. Dawe, Kab. Kudus', 'https://goo.gl/maps/ztUATx6L3GHvfBSPA', 'assets/images/air_terjun_montel.jpg', 'Tempat wisata air terjun ini jufa terbilang cukup ramai karena memang sudah tersedia fasilitas seperti mushola, tempat parkir yang cukup luas, warung yang menjual berbagai macam makanan', 'Wisatawan bisa mendapatkan kesegaran yang luar biasa di air terjun montel ini. Tempat wisata air terjun ini jufa terbilang cukup ramai karena memang sudah tersedia fasilitas seperti mushola, tempat parkir yang cukup luas, warung yang menjual berbagai macam makanan hingga kios dengan aneka cinderamata yang ada.\nLetaknya memang tak jauh daari makam Wali Sunan Muria tepat berada di sebelah utara. Nantinya wisatawan bisa merasakan kesegaran dimana air disini juga bisa diminum karena bersih dan segar. Air Terjun Montel berada di Desa Kajar, Kecamatan Dawe. Letaknya berada di Kabupaten Kudus Jawa Tengah yang memiliki ketinggian air sektiar 50 meter. Wisatawan yang datang dikenakan biaya hanya Rp. 5000 saja per orang.'),
    Models(3, Colors.greenAccent, 'Menara Kudus', 'Jl. Menara, Pejaten, Kauman, Kec. Kota Kudus, Kabupaten Kudus, Jawa Tengah 59315', 'https://goo.gl/maps/VacunwcNRmiNvZv76', 'assets/images/menara_kudus.jpg', 'Menara Kudus ini terkenal menjadi objek wisata dan tak boleh dilewatkan begitu saja.', 'Menjadi wisata religi, tempat ini akan sangat ramai jika pada musim liburan. Menara Kudus ini terkenal menjadi objek wisata dan tak boleh dilewatkan begitu saja. Bangunannya dibuat dari tumpukan batu bata yang beratap kayu dan berbentuk limas. Sementara di bagian dinding menara ini ada beberapa piring logam yang menempel.\nAda cerita yang menyebut bahwa piring tersebut didatangkan langsung dari China. Lokasi Menara Kudus ini berada di depan Masjid Al Aqsa yang berfungsi juga sebagai penanda masuknya waktu sholat. Sementara di sekitaran menara tersebut ada Makam Sunan Kudus jika wisatawan ingin berziarah.'),
    Models(4, Colors.amberAccent, 'Desa Wisata Rahtawu Kudus', 'Area Gn., Rahtawu, Kec. Gebog, Kabupaten Kudus, Jawa Tengah 59333', 'https://goo.gl/maps/knPg3Hb8W8hnyA1k7', 'assets/images/desa_rahtawu.jpg', 'Desa ini memiliki ketinggian 1627 mdpl yang membuat udara begitu sejuk dan segar.', 'Rahtawu juga menjadi tempat wisata yang ada di Kudus. Desa ini memiliki ketinggian 1627 mdpl yang membuat udara begitu sejuk dan segar. Di desa ini juga ada sungai yang begitu jernih dan bisa digunakan untuk mandi serta bermain air. Selain ada pemandangan alam yang begitu indah dan menarik, wisatawan bisa melihat adanya banguann-bangunan pertapaan yang bisa dijelajah.\nLetak desa ini berada di lereng gunung Muria. Tepatnya ada di kecamatan Gebong Kudus yang juga ramai dikunjungi para wisatawan.'),
    Models(5, Colors.cyanAccent, 'Air Tiga Rasa Rejenu', 'Area Gn., Japan, Kec. Dawe, Kabupaten Kudus, Jawa Tengah 59353', 'https://goo.gl/maps/ggnyuCWoC3RofTjg8', 'assets/images/rejenu.jpg', 'Sumber Air Tiga Rasa Rejenu bisa dijadikan sebagai tujuan wisata yang tepat ketika Anda singgah di Kudus.', 'Mengunjungi tempat tempat unik saat liburan akan membuat liburan Anda semakin berkesan. Sumber Air Tiga Rasa Rejenu bisa dijadikan sebagai tujuan wisata yang tepat ketika Anda singgah di Kudus. Sumber air ini dipercaya masyarakat mampu memberikan khasiat yang baik bagi tubuh. sampai saat ini secara turun temurun juga masih dipegang teguh. \nSeperti namanya, masing masing sumber memang memiliki rasa yang berbeda beda. Anda yang penasaran, bisa menjajal sendiri bagaimana rasa dari masing masingnya. Dengan begitu Anda bisa mengetahui apakah memang berbeda atau tidak. Tetapi jangan langsung diminum bersamaan, karena nantinya rasanya akan menjadi tawar layaknya air biasa.'),
    Models(6, Colors.deepOrangeAccent, 'Wisata Bumi Perkemahan Kajar', 'Dersaya, Kajar, Kec. Dawe, Kabupaten Kudus, Jawa Tengah 59353', 'https://goo.gl/maps/gWiPqv5ciP1ziHBi7', 'assets/images/buper_kajar.jpg', 'Tempat ini lokasinya ada di ketinggian 600 mdpl dan memiliki banyak pepohonan pinus.', 'Jika ingin liburan dengan konsep outbound, wisatawan bisa datang ke Bumi Perkemahan dan Wana Wisata Kajar. Layak menjadi destinasi wisata khusus yang spesial karena memang ada kawasan hutan pinus yang lokasinya juga begitu segar. Wisatawan yang datang bisa merasakan bagaimana kesejukan di dalam tempat ini.\nTempat ini lokasinya ada di ketinggian 600 mdpl dan memiliki banyak pepohonan pinus yang mana jaraknya juga sekitar 3 KM dari Makam Sunan Muria. Wana wisata ini juga sering menjadi tujuan pelatihan instansi atau organisasi.'),
    Models(7, Colors.deepPurpleAccent, 'Bendungan Logung', 'Area Sawah, Kandangmas, Kec. Dawe, Kabupaten Kudus, Jawa Tengah 59353', 'https://goo.gl/maps/Lm6WLPg1QA1FJBiV9', 'assets/images/logung.jpg', 'Wisata ini menawarkan wisata mengelilingi waduk dengan menggunakan perahu yang ada.', 'Menikmati liburan di Kudus juga bisa dilakukan dengan mengunjungi Waduk Logung. Destinasi ini menawarkan pemandangan pegunungan Muria yang bisa dinikmati dari atas perahu. Objek wisata satu ini terbilang dekat dari pusat kota, Anda hanya membutuhkan waktu sekitar 27 menit saja untuk sampai. Akses menuju waduk juga mudah untuk Anda jangkau.\nBegitu tiba di lokasi, Anda akan menyaksikan deretan perahu wisata yang bersandar. Wisata ini menawarkan wisata mengelilingi waduk dengan menggunakan perahu yang ada. Dari atas perahu, Anda bisa menikmati pemandangan yang semakin cantik. Panorama akan berlipat lebih cantik ketika sore hari saat matahari berpulang.'),
    Models(8, Colors.indigoAccent, 'Desa Wisata Wonosoco Undaan, Kudus', 'Sawah, Wonosoco, Undaan, Kabupaten Kudus, Jawa Tengah 59372', 'https://goo.gl/maps/peHKZx86Bi3z3ix47', 'assets/images/wonosoco.jpg', 'Memiliki keindahan alam yang buerpa hamparan hijau sawah', 'Desa Wonosoco ini menjadi desa wisata yang cocok dikunjungi selama liburan. Memiliki keindahan alam yang buerpa hamparan hijau sawah dan juga pegunugnan kars kendeng yang membentang dari timur ke barat. Ada banyak objek wisata di desa ini seperti wisata goa, sendaang hingga petilasan. Kegiatan budaya ini juga disuguhkan oleh masyarakat setempat yang secara rutin tiap tahun.\nHarga tiket masuk hanya Rp. 3000 per orang. Wisatawan bisa dimanjakan dengan indahnya pemandangan khas pegunungan dan indahnya alam yang berupa pegunungan Kendeng. Letak Desa Wisata Wonosoco ini berada di selatan kota Kudus. Pengunjung bisa menempuh peralanan sekitar 45 menit dari pusat kota yang juga masuk di kecamatan Undaan.'),
    Models(9, Colors.lightBlueAccent, 'The Hills Vaganza', 'Jl. Raya Kudus - Colo No.KM.13, Watulumpang, Kajar, Kec. Dawe, Kabupaten Kudus, Jawa Tengah 59353', 'https://goo.gl/maps/kGgKK8N2UWQepAUe6', 'assets/images/hill_vaganza.jpg', 'Panorama perbukitan yang asik dengan spot spot foto kekinian menjadi daya tarik tersendiri.', 'The Hills Vaganza menggabungkan konsep resto dan tempat wisata yang kekinian. Panorama perbukitan yang asik dengan spot spot foto kekinian menjadi daya tarik tersendiri. Suasana yang asri dengan udara yang sejuk semakin menambah daftar mengapa destinasi satu ini begitu hits. Pengunjungnya kebanyakan adalah kawula muda dan keluarga.\nHadirnya spot spot foto membuat pengunjung tidak melewatkan untuk mengambil beberapa potret. Beberapa spot yang favorit mulai dari jembatan kayu ala Jepang, bunga sakura, rumah hobbit, payung warna warni dan masih banyak spot lainnya. Selepas berjalan jalan, Anda bisa melanjutkan dengan wisata kuliner yang menggoyang lidah.'),
    Models(10, Colors.limeAccent, 'Museum Purbakala Patiayam', 'Kancilan, Terban, Kec. Jekulo, Kabupaten Kudus, Jawa Tengah 59382', 'https://goo.gl/maps/h1tQEsmmCYfoB6R48', 'assets/images/pati_ayam.jpg', 'Di situs ini ada berbagai macam fosil yang pernah ditemukan oleh warga sekitar.', 'Namanya adalah Situs Pati Ayam. Situs ini menjadi tempat wisata yang ada di Kudus dan menawarkan suasana yang begitu kental dengan sejarah. Di situs ini ada berbagai macam fosil yang pernah ditemukan oleh warga sekitar.\nKawasan Pati Ayam sendiri juga menjadi pusat peradaban manusia purba yang bisa ditemukan berbagai macam fosil disana. Seperti misalnya gading gajah purba, gigi geraham dan masih banyak lagi. Lokasi dari situs ini ada di Desa Terban Kecamatan Jekulo Kabupaten Kudus. Pengunjung bisa melihat fosil binatang dengan ukuran raksasa dan replika manusia purba.'),
    Models(11, Colors.tealAccent, 'Waterpark Mulia Wisata', 'Jl. Raya Kudus - Colo No.KM, RW.12, Lau, Kec. Dawe, Kabupaten Kudus, Jawa Tengah 59353', 'https://g.page/waterparkmuliawisata?share', 'assets/images/waterpark.jpg', 'Pengelola menyediakan berbagai wahana permainan yang seru seperti memancing, ATV hingga kolam berarus.', 'Mereka yang datang ke Kudus seringkali menghabiskan waktu dengan keluarga dan banyak anggota lainnya. Jika memang ingin memanjakan si kecil, Waterboom Mulia Kudus adalah jawabannya. Waterboom ini bisa dijadikan sebagai destinasi liburan yang seru bersama keluarga dan anak-anak. Menjadi salah satu wahana liburan yang memang wajib untuk dikunjungi.\nPengelola menyediakan berbagai wahana permainan yang seru seperti memancing, ATV hingga kolam berarus. Ketika akhir pekan tempat ini cukup ramai. Waterboom Mulia Kudus ini berada di Jalan Kudus-Colo KM 12, Desa lau Kecamatan Bae Kudus. Tiket masuk yang dibayarkan hanya sebesar Rp. 15.000 per orang.')
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        title: new Text("Visit Kudus"),
      ),
      body: ListView.builder(
        padding: EdgeInsets.only(bottom: 24),
        itemCount: data.length,
        itemBuilder: (BuildContext context, int index) {
          return Items(index, data[index], (modelData) {
            print(modelData.name + ' Clicked');
            Navigator.push(context, MaterialPageRoute(builder: (context){
              return DetailsPage(modelData);
            }));
          });
        },
      ),
    );
  }
}
